"""Patrons de formulation par intention."""

from .taxonomie import Intention

PATRONS_ENTRAINEMENT: dict[Intention, tuple[str, ...]] = {
    Intention.DEGAT_DES_EAUX: (
        "fuite d'eau {localisation} de la {chambre}",
        "il y a une fuite dans la {chambre}",
        "de l'eau coule {localisation} en {chambre}",
        "la {chambre} est inondee",
        "infiltration signalee {chambre}",
        "le client de la {chambre} signale une fuite",
        "eau au sol dans la {chambre}",
        "fuite {localisation} chambre {chambre}",
        "la {chambre} prend l'eau {localisation}",
        "ca fuit {localisation} de la {chambre}",
        "grosse fuite constatee dans la {chambre}",
        "on signale de l'eau {localisation} en {chambre}",
        "la {chambre} presente une infiltration {localisation}",
        "urgence plomberie, la {chambre} est noyee",
        "le sol de la {chambre} est detrempe",
        "un ecoulement se produit {localisation} chambre {chambre}",
        "la {chambre} doit etre vidangee, il y a de l'eau",
        "arrivee d'eau incontrolee en {chambre}",
        "le client de la {chambre} a les pieds dans l'eau",
        "probleme grave d'eau {localisation} en {chambre}",
        "la {chambre} n'est plus habitable, fuite {localisation}",
        "signalement urgent, eau dans la {chambre}",
        "l'eau s'accumule {localisation} de la {chambre}",
        "il pleut {localisation} de la {chambre}",
        "la {chambre} est touchee par une fuite",
        "l'etancheite a cede {localisation} en {chambre}",
        "eau stagnante relevee dans la {chambre}",
        "on constate un suintement {localisation} chambre {chambre}",
        "la {chambre} subit un degat des eaux",
        "intervention demandee, fuite {chambre}",
    ),
    Intention.PANNE_CLIMATISATION: (
        "la clim de la {chambre} ne marche plus",
        "climatisation en panne {chambre}",
        "la {chambre} n'a plus de climatisation",
        "probleme de clim en {chambre}",
        "clim hs {chambre}",
        "la climatisation de la {chambre} ne demarre pas",
        "pas de froid dans la {chambre}",
        "la clim souffle chaud en {chambre}",
        "la {chambre} etouffe, plus de clim",
        "l'appareil de climatisation de la {chambre} est arrete",
        "aucune ventilation dans la {chambre}",
        "la clim de la {chambre} tourne sans refroidir",
        "il fait une chaleur insupportable en {chambre}",
        "climatisation a reparer chambre {chambre}",
        "la {chambre} signale un dysfonctionnement de clim",
        "plus aucun reglage de temperature en {chambre}",
        "la clim s'arrete toute seule dans la {chambre}",
        "systeme de climatisation defaillant {chambre}",
        "le client de la {chambre} reclame pour la clim",
        "la {chambre} n'est plus climatisee",
        "panne de ventilation en {chambre}",
        "la clim de la {chambre} fuit et ne refroidit plus",
        "temperature ingerable dans la {chambre}",
        "clim en derangement chambre {chambre}",
        "le groupe froid de la {chambre} est arrete",
        "impossible de rafraichir la {chambre}",
        "la {chambre} demande une intervention sur la clim",
        "climatisation muette en {chambre}",
    ),
    Intention.AGENT_INDISPONIBLE: (
        "{agent} est absent aujourd'hui",
        "{agent} ne viendra pas travailler",
        "l'agent {agent} est en arret",
        "{agent} du secteur {secteur} est absent",
        "on n'a plus {agent} sur {secteur}",
        "absence de {agent}",
        "il manque {agent} sur le secteur {secteur}",
        "l'agent {agent} n'a pas pris son service",
        "on ne compte plus sur {agent} aujourd'hui",
        "{agent} s'est fait porter pale",
        "l'equipe de {secteur} perd {agent}",
        "prevoir sans {agent} sur {secteur}",
        "{agent} ne repond pas, probablement absent",
        "indisponibilite de {agent} signalee",
        "il faut reorganiser, {agent} manque",
        "{agent} a un souci et ne prend pas son poste",
        "le secteur {secteur} tourne sans {agent}",
        "{agent} est declare indisponible",
        "aucun signe de {agent} ce matin",
        "{agent} a pose un arret de travail",
        "l'effectif de {secteur} est ampute de {agent}",
        "{agent} ne sera pas la de la journee",
        "absence non prevue de {agent} sur {secteur}",
        "{agent} previent d'un retard important",
        "on doit couvrir le poste de {agent}",
        "{agent} est retenu et ne viendra pas",
        "defection de {agent} sur le secteur {secteur}",
        "plus d'agent {agent} disponible",
    ),
    Intention.PANNE_ELECTRIQUE: (
        "plus d'electricite dans la {chambre}",
        "panne de courant {chambre}",
        "la {chambre} n'a plus de lumiere",
        "coupure electrique en {chambre}",
        "les prises de la {chambre} ne fonctionnent plus",
        "probleme electrique signale {chambre}",
        "disjoncteur saute en {chambre}",
        "le client de la {chambre} n'a plus de courant",
        "la {chambre} est privee de courant",
        "black-out signale en {chambre}",
        "aucune alimentation electrique chambre {chambre}",
        "le circuit de la {chambre} a saute",
        "plus rien ne s'allume dans la {chambre}",
        "panne generale d'electricite en {chambre}",
        "les lampes de la {chambre} restent eteintes",
        "courant absent dans la {chambre}",
        "defaut electrique constate chambre {chambre}",
        "la {chambre} n'a plus d'alimentation",
        "coupure totale en {chambre}",
        "le client de la {chambre} est sans lumiere",
        "installation electrique hors service {chambre}",
        "la {chambre} demande une intervention electrique",
        "plus de courant aux prises de la {chambre}",
        "electricite coupee chambre {chambre}",
        "la {chambre} est dans le noir complet",
        "dysfonctionnement electrique en {chambre}",
        "le disjoncteur de la {chambre} ne tient plus",
        "alimentation defaillante dans la {chambre}",
    ),
    Intention.PANNE_PLOMBERIE: (
        "le lavabo de la {chambre} est bouche",
        "probleme de plomberie {localisation} en {chambre}",
        "la douche de la {chambre} ne s'ecoule plus",
        "wc bouches {chambre}",
        "pas d'eau chaude dans la {chambre}",
        "evacuation bouchee {localisation} chambre {chambre}",
        "la robinetterie de la {chambre} est defectueuse",
        "chasse d'eau hs en {chambre}",
        "l'eau ne s'evacue plus {localisation} en {chambre}",
        "engorgement signale chambre {chambre}",
        "la {chambre} n'a plus de pression d'eau",
        "probleme sanitaire {localisation} dans la {chambre}",
        "le siphon de la {chambre} est obstrue",
        "la douche de la {chambre} deborde",
        "plomberie a revoir {localisation} chambre {chambre}",
        "aucun ecoulement en {chambre}",
        "le client de la {chambre} n'a pas d'eau chaude",
        "les sanitaires de la {chambre} sont hors service",
        "canalisation bouchee {localisation} en {chambre}",
        "la {chambre} signale un refoulement",
        "robinet bloque dans la {chambre}",
        "eau froide seulement en {chambre}",
        "la {chambre} demande une intervention plomberie",
        "evier obstrue {localisation} chambre {chambre}",
        "la chasse de la {chambre} ne se remplit plus",
        "fuite au niveau du robinet de la {chambre}",
        "installation sanitaire defaillante en {chambre}",
        "la {chambre} a un probleme d'evacuation {localisation}",
    ),
    Intention.DEFAUT_SERRURE: (
        "la serrure de la {chambre} ne fonctionne plus",
        "impossible d'ouvrir la {chambre}",
        "le badge ne marche pas sur la {chambre}",
        "probleme de cle en {chambre}",
        "la porte de la {chambre} ne ferme plus",
        "serrure bloquee {chambre}",
        "le client de la {chambre} n'arrive pas a entrer",
        "verrou defectueux chambre {chambre}",
        "le client de la {chambre} est bloque dehors",
        "carte magnetique refusee sur la {chambre}",
        "mecanisme de fermeture defaillant chambre {chambre}",
        "la porte de la {chambre} reste ouverte",
        "on ne peut plus verrouiller la {chambre}",
        "le lecteur de la {chambre} clignote rouge",
        "acces impossible a la {chambre}",
        "serrure a remplacer sur la {chambre}",
        "la cle de la {chambre} tourne dans le vide",
        "probleme de fermeture en {chambre}",
        "la {chambre} ne se securise plus",
        "le pene de la {chambre} est bloque",
        "badge non reconnu chambre {chambre}",
        "ouverture forcee necessaire pour la {chambre}",
        "la {chambre} demande une intervention serrurerie",
        "dysfonctionnement du verrou en {chambre}",
        "la poignee de la {chambre} tourne sans effet",
        "impossible de condamner la {chambre}",
        "systeme d'acces hors service {chambre}",
        "le client ne peut pas entrer en {chambre}",
    ),
    Intention.MOBILIER_ENDOMMAGE: (
        "le fauteuil de la {chambre} est casse",
        "mobilier endommage {localisation} en {chambre}",
        "la {chambre} a un meuble abime",
        "tiroir casse dans la {chambre}",
        "le bureau de la {chambre} est raye",
        "degradation constatee {localisation} chambre {chambre}",
        "la television de la {chambre} est tombee",
        "lit abime en {chambre}",
        "meuble casse a remplacer en {chambre}",
        "le client de la {chambre} signale une degradation",
        "equipement abime {localisation} de la {chambre}",
        "la chaise de la {chambre} est hors d'usage",
        "revetement arrache {localisation} chambre {chambre}",
        "la table de nuit de la {chambre} est cassee",
        "mobilier a reparer en {chambre}",
        "l'armoire de la {chambre} ne ferme plus",
        "degradation constatee en {chambre}",
        "le canape de la {chambre} est tache et dechire",
        "element de mobilier defectueux chambre {chambre}",
        "la {chambre} necessite un remplacement de meuble",
        "vitrage du meuble brise en {chambre}",
        "le lit de la {chambre} grince et penche",
        "usure excessive {localisation} de la {chambre}",
        "materiel endommage signale {chambre}",
        "la {chambre} presente du mobilier detériore",
        "pied casse sur un meuble de la {chambre}",
        "rangement inutilisable en {chambre}",
        "reparation mobilier demandee chambre {chambre}",
    ),
    Intention.NUISANCE_SONORE: (
        "bruit important dans la {chambre}",
        "le client de la {chambre} se plaint du bruit",
        "nuisance sonore signalee {chambre}",
        "la {chambre} est trop bruyante",
        "plainte pour tapage en {chambre}",
        "il y a du vacarme dans la {chambre}",
        "bruits de travaux genent la {chambre}",
        "la {chambre} entend tout du couloir",
        "reclamation pour bruit chambre {chambre}",
        "le voisinage derange la {chambre}",
        "tapage nocturne signale en {chambre}",
        "la {chambre} ne peut pas dormir a cause du bruit",
        "nuisance persistante dans la {chambre}",
        "bruit de tuyauterie genant la {chambre}",
        "le client de la {chambre} demande un autre etage, trop bruyant",
        "vacarme continu en {chambre}",
        "isolation phonique insuffisante chambre {chambre}",
        "la {chambre} subit des nuisances repetees",
        "plainte sonore deposee pour la {chambre}",
        "bruits de pas incessants au-dessus de la {chambre}",
        "la {chambre} entend la ventilation en permanence",
        "gene acoustique signalee en {chambre}",
        "musique trop forte pres de la {chambre}",
        "la {chambre} est expose au bruit de la rue",
        "reclamation acoustique chambre {chambre}",
        "impossible de se reposer en {chambre}",
        "bruit anormal detecte dans la {chambre}",
        "le calme n'est pas assure en {chambre}",
    ),
    Intention.RISQUE_SECURITE: (
        "odeur de gaz {localisation} en {chambre}",
        "risque de securite signale {chambre}",
        "detecteur de fumee declenche en {chambre}",
        "cable electrique denude {localisation} chambre {chambre}",
        "danger immediat dans la {chambre}",
        "depart de feu suspecte en {chambre}",
        "la {chambre} presente un risque pour le client",
        "vitre brisee {localisation} en {chambre}",
        "danger signale {localisation} en {chambre}",
        "la {chambre} doit etre condamnee immediatement",
        "installation a risque chambre {chambre}",
        "fumee constatee {localisation} de la {chambre}",
        "alerte securite pour la {chambre}",
        "situation dangereuse en {chambre}",
        "la {chambre} presente un peril pour l'occupant",
        "evacuation preventive de la {chambre}",
        "anomalie grave relevee {localisation} chambre {chambre}",
        "risque d'accident en {chambre}",
        "la {chambre} n'est pas securisee",
        "element dangereux {localisation} dans la {chambre}",
        "intervention urgente securite {chambre}",
        "la {chambre} doit etre inspectee sans delai",
        "manquement a la securite constate en {chambre}",
        "odeur suspecte {localisation} de la {chambre}",
        "la {chambre} presente un danger electrique",
        "signalement securite prioritaire chambre {chambre}",
        "acces a interdire pour la {chambre}",
        "menace pour l'integrite du client en {chambre}",
    ),
    Intention.DEMANDE_AFFECTATION: (
        "quelle chambre pour {reservation}",
        "il faut affecter une chambre a {reservation}",
        "{reservation} arrive sans chambre",
        "trouver une chambre pour {reservation} avec {equipement}",
        "affectation a faire pour {reservation}",
        "on doit loger {reservation}",
        "chambre a attribuer a {reservation}",
        "{reservation} demande une chambre avec {equipement}",
        "loger {reservation} qui arrive",
        "il faut une chambre pour {reservation}",
        "attribution en attente pour {reservation}",
        "{reservation} n'a toujours pas de chambre",
        "prevoir l'hebergement de {reservation}",
        "quelle chambre convient a {reservation}",
        "traiter l'affectation de {reservation}",
        "{reservation} necessite une chambre avec {equipement}",
        "chercher un logement pour {reservation}",
        "{reservation} est en attente d'attribution",
        "chambre a designer pour {reservation}",
        "l'arrivee {reservation} reste sans solution",
        "affecter {reservation} au plus vite",
        "{reservation} demande {equipement} dans sa chambre",
        "trouver ou installer {reservation}",
        "placement a faire pour {reservation}",
        "{reservation} arrive et rien n'est prevu",
        "designer une chambre a {reservation}",
        "il reste {reservation} sans hebergement",
        "attribuer une chambre disposant de {equipement} a {reservation}",
    ),
    Intention.DEMANDE_AVEC_PREFERENCE: (
        "il me faut une chambre a cote de la {proximite}",
        "trouve une chambre pres de la {proximite}",
        "une chambre voisine de la {proximite}",
        "je veux une chambre proche de la {proximite}",
        "chercher une chambre a proximite de la {proximite}",
        "une chambre juste a cote de la {proximite}",
        "loger le client pres de la {proximite}",
        "une chambre au meme etage que la {proximite}",
        "il faut une chambre a l'etage {etage}",
        "trouve une chambre a l'etage {etage}",
        "une chambre situee a l'etage {etage}",
        "je souhaite une chambre loin de la {eloignement}",
        "eloigner le client de la {eloignement}",
        "une chambre a distance de la {eloignement}",
        "surtout pas a cote de la {eloignement}",
        "une chambre proche de la {proximite} pour {reservation}",
        "{reservation} veut etre pres de la {proximite}",
        "placer {reservation} a cote de la {proximite}",
        "{reservation} demande l'etage {etage}",
        "une chambre voisine de la {proximite} si possible",
    ),
    Intention.INCIDENT_AVEC_PREFERENCE: (
        "il y a une fuite dans la {chambre}, il me faut une chambre a cote de la {proximite}",
        "la {chambre} a un souci et je veux une chambre pres de la {proximite}",
        "probleme dans la {chambre}, trouve une chambre voisine de la {proximite}",
        "panne en {chambre}, reloger le client pres de la {proximite}",
        "la {chambre} est inondee, une chambre proche de la {proximite}",
        "incident sur la {chambre}, chambre de remplacement a l'etage {etage}",
        "la {chambre} est hors service, il faut une chambre a l'etage {etage}",
        "degat dans la {chambre}, une chambre au meme etage si possible",
        "la {chambre} a un probleme, eloigner le client de la {eloignement}",
        "souci technique en {chambre}, chambre voisine de la {proximite}",
        "la {chambre} doit etre liberee, prevoir pres de la {proximite}",
        "la clim de la {chambre} est morte, une chambre a cote de la {proximite}",
        "fuite en {chambre}, le client veut rester a l'etage {etage}",
        "la {chambre} est inutilisable, chambre proche de la {proximite}",
        "avarie en {chambre}, reloger a proximite de la {proximite}",
        "la {chambre} est bloquee, une chambre a l'etage {etage} de preference",
        "incident {chambre}, surtout pas a cote de la {eloignement}",
        "la {chambre} prend l'eau, chambre voisine de la {proximite}",
        "defaut sur la {chambre}, prevoir une chambre pres de la {proximite}",
        "la {chambre} est immobilisee, chambre a l'etage {etage}",
    ),
    Intention.CHANGEMENT_AVEC_PREFERENCE: (
        "deplacer {reservation} de la {chambre} vers une chambre pres de la {proximite}",
        "changer {reservation} pour une chambre a l'etage {etage}",
        "{reservation} veut quitter la {chambre} et etre pres de la {proximite}",
        "reloger {reservation} a cote de la {proximite}",
        "{reservation} demande une chambre voisine de la {proximite}",
        "transferer {reservation} vers l'etage {etage}",
        "{reservation} souhaite s'eloigner de la {eloignement}",
        "muter {reservation} de la {chambre} a l'etage {etage}",
        "{reservation} veut une autre chambre proche de la {proximite}",
        "sortir {reservation} de la {chambre}, chambre pres de la {proximite}",
        "{reservation} demande a changer pour l'etage {etage}",
        "permuter {reservation} vers une chambre voisine de la {proximite}",
        "{reservation} ne veut plus etre pres de la {eloignement}",
        "reaffecter {reservation} a proximite de la {proximite}",
        "{reservation} quitte la {chambre} pour l'etage {etage}",
        "trouver a {reservation} une chambre a cote de la {proximite}",
        "{reservation} veut le meme etage que la {proximite}",
        "deplacer {reservation} loin de la {eloignement}",
        "{reservation} change de la {chambre} vers pres de la {proximite}",
        "nouvelle chambre pour {reservation} a l'etage {etage}",
    ),
    Intention.DEMANDE_CHANGEMENT: (
        "il faut deplacer {reservation} de la {chambre}",
        "changement de chambre pour {reservation}",
        "{reservation} veut quitter la {chambre}",
        "reloger {reservation} qui est en {chambre}",
        "la {chambre} ne convient pas a {reservation}",
        "{reservation} demande une autre chambre avec {equipement}",
        "transferer {reservation} hors de la {chambre}",
        "le client de la {chambre} souhaite changer",
        "{reservation} souhaite quitter la {chambre}",
        "reloger le client de la {chambre}",
        "la {chambre} ne satisfait pas {reservation}",
        "prevoir une permutation pour {reservation}",
        "{reservation} demande a changer de la {chambre}",
        "deplacer l'occupant de la {chambre}",
        "changement demande par {reservation}",
        "{reservation} veut une chambre avec {equipement}",
        "sortir {reservation} de la {chambre}",
        "reaffecter {reservation} actuellement en {chambre}",
        "le sejour {reservation} doit etre transfere",
        "la {chambre} pose probleme a {reservation}",
        "prevoir un autre hebergement pour {reservation}",
        "{reservation} reclame un changement de chambre",
        "muter {reservation} vers une autre chambre",
        "le client {reservation} refuse la {chambre}",
        "attribuer une nouvelle chambre a {reservation}",
        "la {chambre} doit etre liberee pour {reservation}",
        "{reservation} demande {equipement}, la {chambre} n'en a pas",
        "transfert a organiser depuis la {chambre}",
    ),
    Intention.SIGNALEMENT_INDISPONIBILITE: (
        "la {chambre} est indisponible",
        "bloquer la {chambre}",
        "mettre la {chambre} hors service",
        "la {chambre} ne peut plus etre louee",
        "retirer la {chambre} de la vente",
        "chambre {chambre} immobilisee",
        "ne plus attribuer la {chambre}",
        "la {chambre} passe en maintenance",
        "la {chambre} sort du parc",
        "ne plus proposer la {chambre}",
        "immobiliser la {chambre} jusqu'a reparation",
        "la {chambre} est inexploitable",
        "suspendre la {chambre}",
        "marquer la {chambre} comme indisponible",
        "la {chambre} ne doit plus recevoir de client",
        "exclure la {chambre} des affectations",
        "la {chambre} passe hors exploitation",
        "condamner temporairement la {chambre}",
        "la {chambre} n'est plus commercialisable",
        "geler la {chambre} pour intervention",
        "retirer la {chambre} du planning",
        "la {chambre} devient inoccupable",
        "interdire l'attribution de la {chambre}",
        "la {chambre} est mise a l'ecart",
        "bloquer definitivement la {chambre}",
        "la {chambre} est retiree de la disponibilite",
        "cesser de louer la {chambre}",
        "la {chambre} requiert une immobilisation",
    ),
    Intention.ARRIVEE_ANTICIPEE: (
        "{reservation} arrive a {heure}",
        "arrivee anticipee de {reservation} vers {heure}",
        "{reservation} se presente des {heure}",
        "le client {reservation} sera la a {heure}",
        "{reservation} annonce une arrivee a {heure}",
        "arrivee avancee pour {reservation}",
        "{reservation} arrive plus tot que prevu, {heure}",
        "prevenir que {reservation} vient a {heure}",
        "{reservation} sera la des {heure}",
        "avancer l'arrivee de {reservation} a {heure}",
        "{reservation} demande a entrer a {heure}",
        "le client {reservation} arrive tot, {heure}",
        "presentation anticipee de {reservation}",
        "{reservation} previent qu'il arrive vers {heure}",
        "arrivee revue a {heure} pour {reservation}",
        "{reservation} souhaite acceder des {heure}",
        "prevoir {reservation} pour {heure}",
        "le sejour {reservation} commence a {heure}",
        "{reservation} devance l'horaire, {heure}",
        "arrivee plus matinale de {reservation}",
        "{reservation} se presentera a {heure}",
        "horaire avance signale pour {reservation}",
        "{reservation} arrive avant l'heure prevue",
        "acces demande a {heure} par {reservation}",
        "{reservation} annonce {heure} comme arrivee",
        "anticiper l'accueil de {reservation} a {heure}",
        "le client {reservation} est attendu des {heure}",
        "modification d'horaire pour {reservation}, {heure}",
    ),
    Intention.CHAMBRE_URGENTE: (
        "la {chambre} doit etre prete pour {heure}",
        "preparer la {chambre} en urgence",
        "il faut la {chambre} avant {heure}",
        "nettoyage prioritaire pour la {chambre}",
        "la {chambre} est attendue a {heure}",
        "faire passer la {chambre} en priorite",
        "chambre {chambre} urgente pour {heure}",
        "traiter la {chambre} en premier",
        "la {chambre} passe en priorite absolue",
        "il faut la {chambre} au plus vite",
        "traiter la {chambre} avant {heure}",
        "la {chambre} est attendue en urgence",
        "nettoyer la {chambre} en premier",
        "la {chambre} doit etre livree pour {heure}",
        "prioriser le nettoyage de la {chambre}",
        "la {chambre} est reclamee immediatement",
        "avancer la preparation de la {chambre}",
        "remise en etat urgente de la {chambre}",
        "la {chambre} devient prioritaire pour {heure}",
        "faire la {chambre} sans attendre",
        "urgence sur la {chambre}",
        "la {chambre} doit etre disponible a {heure}",
        "placer la {chambre} en tete du planning",
        "preparation immediate demandee chambre {chambre}",
        "la {chambre} ne peut pas attendre",
        "traitement prioritaire pour la {chambre}",
        "la {chambre} est requise pour {heure}",
        "acceler la mise en ordre de la {chambre}",
    ),
    Intention.DEMANDE_PLANIFICATION: (
        "organiser le service du secteur {secteur}",
        "planifier le nettoyage sur {secteur}",
        "il faut faire le planning de {secteur}",
        "repartir les chambres du secteur {secteur}",
        "planification demandee pour {secteur}",
        "organiser les etages sur {secteur}",
        "faire le tour de service de {secteur}",
        "affecter les taches du secteur {secteur}",
        "etablir le planning du secteur {secteur}",
        "repartir le travail sur {secteur}",
        "organiser les taches de {secteur}",
        "planifier les chambres du secteur {secteur}",
        "il faut ordonner le service de {secteur}",
        "distribuer les prestations sur {secteur}",
        "preparer la journee du secteur {secteur}",
        "affecter les agents de {secteur}",
        "quel planning pour {secteur}",
        "organiser le nettoyage du secteur {secteur}",
        "calculer le tour de service de {secteur}",
        "le secteur {secteur} attend son planning",
        "repartition a faire sur {secteur}",
        "ordonnancer les taches du secteur {secteur}",
        "mettre en place le service de {secteur}",
        "planification du secteur {secteur} demandee",
        "attribuer les chambres aux agents de {secteur}",
        "structurer la journee de {secteur}",
        "il faut planifier {secteur}",
        "definir l'ordre de passage sur {secteur}",
    ),
    Intention.CONSULTER_PARC: (
        "combien de chambres avons-nous",
        "quel est le nombre de chambres",
        "combien de chambres compte l'hotel",
        "quelle est la taille du parc",
        "donne moi le nombre total de chambres",
        "on a combien de chambres en tout",
        "quel est l'effectif du parc",
        "combien de chambres au total",
        "je veux connaitre le nombre de chambres",
        "quelle est la capacite de l'etablissement",
        "combien de chambres sont enregistrees",
        "affiche le nombre de chambres",
        "l'hotel dispose de combien de chambres",
        "quel est le parc de l'etablissement",
        "nombre de chambres",
        "on gere combien de chambres",
        "quelle quantite de chambres avons nous",
        "combien de chambres au total dans l'hotel",
        "donne le total des chambres",
        "quel est le volume du parc",
    ),
    Intention.CONSULTER_DISPONIBILITE: (
        "quelles chambres sont disponibles",
        "combien de chambres sont libres",
        "quelles chambres sont libres a l'etage {etage}",
        "montre moi les chambres disponibles",
        "on a quoi de libre",
        "quelles chambres puis je proposer",
        "combien de chambres disponibles a l'etage {etage}",
        "liste des chambres libres",
        "qu'est ce qui est disponible",
        "quelles chambres sont pretes",
        "il reste combien de chambres",
        "affiche les disponibilites",
        "quelles chambres libres a l'etage {etage}",
        "on a des chambres de libre",
        "combien de chambres puis je vendre",
        "quel est le stock disponible",
        "montre les chambres pretes a l'etage {etage}",
        "disponibilites du jour",
        "quelles chambres sont attribuables",
        "j'ai besoin de la liste des chambres libres",
    ),
    Intention.CONSULTER_INDISPONIBLES: (
        "quelles chambres sont hors service",
        "quelles chambres sont hors service a l'etage {etage}",
        "combien de chambres sont bloquees",
        "montre moi les chambres indisponibles",
        "quelles chambres sont immobilisees",
        "liste des chambres hors service",
        "quelles chambres ne sont pas louables",
        "combien de chambres bloquees a l'etage {etage}",
        "affiche les chambres en maintenance",
        "quelles chambres sont condamnees",
        "on a combien de chambres hors service",
        "quelles chambres sont retirees de la vente",
        "liste des immobilisations a l'etage {etage}",
        "quelles chambres ne peuvent pas etre attribuees",
        "montre les chambres bloquees",
        "quelles chambres sont en panne",
        "combien de chambres inexploitables",
        "quelles chambres sont a reparer a l'etage {etage}",
        "affiche les indisponibilites",
        "quelles chambres sont hors exploitation",
    ),
    Intention.CONSULTER_ARRIVEES: (
        "quelles sont les arrivees du jour",
        "combien de clients arrivent aujourd'hui",
        "qui arrive aujourd'hui",
        "liste des arrivees",
        "combien d'arrivees avant {heure}",
        "quelles arrivees restent a traiter",
        "on attend combien de clients",
        "affiche les arrivees prevues",
        "qui arrive avant {heure}",
        "quelles sont les arrivees a traiter",
        "combien de clients attendus",
        "montre moi les arrivees du jour",
        "quelles reservations arrivent",
        "il y a combien d'arrivees",
        "liste des clients attendus a {heure}",
        "quelles arrivees sans chambre",
        "combien de sejours commencent aujourd'hui",
        "affiche le planning des arrivees",
        "qui doit etre accueilli aujourd'hui",
        "quelles sont les arrivees anticipees",
    ),
    Intention.CONSULTER_AGENTS: (
        "quels agents travaillent aujourd'hui",
        "combien d'agents sont en service",
        "qui travaille sur {secteur}",
        "liste des agents disponibles",
        "combien d'agents sur {secteur}",
        "quels agents sont affectables",
        "on a combien d'agents",
        "affiche les agents en service",
        "qui est present aujourd'hui",
        "quels agents couvrent {secteur}",
        "combien de personnel disponible",
        "montre moi l'effectif",
        "quels sont les agents du secteur {secteur}",
        "qui est de service",
        "liste du personnel present",
        "combien d'agents disponibles sur {secteur}",
        "quel est l'effectif du jour",
        "affiche les agents affectables",
        "quels agents peuvent intervenir",
        "qui compose l'equipe de {secteur}",
    ),
    Intention.CONSULTER_TACHES: (
        "combien de taches restent a faire",
        "quelles taches sont en attente",
        "combien de chambres a nettoyer",
        "quelles taches sur {secteur}",
        "liste des taches du jour",
        "il reste combien de chambres a faire",
        "affiche les taches en attente",
        "combien de nettoyages a planifier",
        "quelles chambres restent a traiter sur {secteur}",
        "quel est le volume de travail",
        "combien de prestations prevues",
        "montre moi les taches de {secteur}",
        "quelles taches ne sont pas affectees",
        "combien de chambres attendent un nettoyage",
        "affiche la charge de {secteur}",
        "quel est le reste a faire",
        "combien de taches sur le secteur {secteur}",
        "liste des prestations en attente",
        "quelles taches sont prioritaires",
        "quel travail reste sur {secteur}",
    ),
    Intention.CONSULTER_CHAMBRE: (
        "quel est l'etat de la {chambre}",
        "donne moi les informations de la {chambre}",
        "la {chambre} est elle libre",
        "affiche la {chambre}",
        "que sais tu de la {chambre}",
        "la {chambre} est disponible",
        "quel est le statut de la {chambre}",
        "montre moi la {chambre}",
        "la {chambre} est elle prete",
        "informations sur la chambre {chambre}",
        "la {chambre} est occupee",
        "quelle est la categorie de la {chambre}",
        "detail de la {chambre}",
        "la {chambre} dispose de quoi",
        "situation de la {chambre}",
        "qui occupe la {chambre}",
        "la {chambre} est elle attribuable",
        "etat technique de la {chambre}",
        "que contient la {chambre}",
        "consulte la {chambre}",
    ),
    Intention.CONSULTER_SEJOUR: (
        "quel est le detail de {reservation}",
        "donne moi les informations de {reservation}",
        "affiche {reservation}",
        "que demande {reservation}",
        "quelle chambre pour {reservation} actuellement",
        "informations sur le sejour {reservation}",
        "quelles sont les exigences de {reservation}",
        "montre moi {reservation}",
        "quand arrive {reservation}",
        "detail du sejour {reservation}",
        "combien de personnes pour {reservation}",
        "quelle categorie pour {reservation}",
        "consulte la reservation {reservation}",
        "situation de {reservation}",
        "{reservation} a t il une chambre",
        "quelles dates pour {reservation}",
        "affiche le dossier {reservation}",
        "que sais tu de {reservation}",
        "statut de {reservation}",
        "profil du sejour {reservation}",
    ),
    Intention.CONFLIT_AFFECTATION: (
        "deux clients ont reserve la {chambre}",
        "il y a un conflit sur la {chambre}",
        "la {chambre} est attribuee deux fois",
        "{reservation} et un autre client sont sur la {chambre}",
        "double reservation sur la {chambre}",
        "deux sejours se chevauchent sur la {chambre}",
        "la {chambre} a deux occupants prevus",
        "conflit d'affectation sur la {chambre}",
        "on a attribue la {chambre} a deux personnes",
        "probleme, la {chambre} est prise deux fois",
        "{reservation} arrive mais la {chambre} est deja occupee",
        "collision de reservations sur la {chambre}",
        "la {chambre} apparait dans deux dossiers",
        "erreur d'attribution sur la {chambre}",
        "deux reservations pour la meme chambre {chambre}",
        "il y a doublon sur la {chambre}",
        "que faire, la {chambre} est reservee deux fois",
        "la {chambre} pose un conflit avec {reservation}",
        "chevauchement detecte sur la {chambre}",
        "on ne peut pas loger les deux en {chambre}",
    ),
    Intention.SUR_OCCUPATION: (
        "l'hotel est complet et un client se presente",
        "nous sommes en surbooking",
        "il n'y a plus de chambre disponible",
        "on a plus de clients que de chambres",
        "situation de sur occupation a {heure}",
        "l'etablissement affiche complet",
        "que faire, nous sommes pleins",
        "trop de reservations pour le parc",
        "nous depassons la capacite",
        "il manque des chambres pour les arrivees",
        "on ne peut pas loger tout le monde",
        "capacite depassee pour aujourd'hui",
        "plus aucune chambre pour les arrivees de {heure}",
        "surbooking constate",
        "l'hotel est saturé",
        "comment gerer le complet",
        "les reservations excedent les chambres",
        "on est en depassement",
        "aucune chambre pour les derniers arrivants",
        "situation critique, etablissement plein",
    ),
    Intention.DEMANDE_CONSEIL: (
        "que dois je faire",
        "comment gerer cette situation",
        "quelle est la meilleure option",
        "que me conseilles tu",
        "comment proceder",
        "quelle decision prendre",
        "aide moi a decider",
        "quelle solution proposes tu",
        "comment resoudre ce probleme",
        "que recommandes tu",
        "quelle est la marche a suivre",
        "comment traiter ce cas",
        "quelles sont mes options",
        "que puis je faire",
        "donne moi une recommandation",
        "comment m'y prendre",
        "quelle conduite adopter",
        "que faire dans ce cas",
        "quelle est la bonne decision",
        "conseille moi",
    ),
    Intention.REPARTIR_CHARGE: (
        "j'ai {quantite} chambres a faire et {quantite} agents, comment repartir",
        "comment repartir {quantite} chambres entre {quantite} agents",
        "{quantite} chambres a nettoyer avec {quantite} personnes",
        "repartir {quantite} chambres sur {quantite} agents",
        "on a {quantite} chambres et seulement {quantite} agents disponibles",
        "quelle repartition pour {quantite} chambres et {quantite} agents",
        "comment organiser {quantite} chambres avec {quantite} agents",
        "distribuer {quantite} chambres entre {quantite} personnes",
        "{quantite} agents pour {quantite} chambres, quelle organisation",
        "aide moi a repartir {quantite} chambres sur {quantite} equipes",
        "il reste {quantite} chambres et j'ai {quantite} agents",
        "comment affecter {quantite} agents sur {quantite} chambres",
        "repartition optimale de {quantite} chambres entre {quantite} agents",
        "quelle charge par agent pour {quantite} chambres",
        "je dois traiter {quantite} chambres avec {quantite} agents",
        "organiser {quantite} nettoyages avec {quantite} personnes",
        "comment equilibrer {quantite} chambres sur {quantite} agents",
        "avec {quantite} agents, comment traiter {quantite} chambres",
        "partager {quantite} chambres entre {quantite} agents",
        "quelle repartition pour gagner du temps sur {quantite} chambres",
    ),
    Intention.CONSULTER_CHARGE: (
        "combien de temps pour finir le secteur {secteur}",
        "quelle est la charge du secteur {secteur}",
        "combien de temps reste-t-il sur {secteur}",
        "quel est le volume de travail sur {secteur}",
        "combien d'heures pour terminer {secteur}",
        "quelle charge pese sur {secteur}",
        "estimation du temps restant sur {secteur}",
        "combien de temps pour boucler {secteur}",
        "quelle est la duree prevue pour {secteur}",
        "on en a pour combien de temps sur {secteur}",
        "quel est le temps de travail restant",
        "combien de temps pour finir les chambres",
        "quelle charge globale aujourd'hui",
        "estimation de la duree totale du service",
        "combien d'heures de nettoyage prevues",
        "quel volume horaire pour le secteur {secteur}",
        "temps estime pour achever {secteur}",
        "combien de temps de travail sur {secteur}",
        "quelle duree pour terminer les taches",
        "combien de temps avant la fin du service",
    ),
    Intention.ESTIMER_FAISABILITE: (
        "peut-on tout finir avant {heure}",
        "est-ce qu'on aura fini pour {heure}",
        "arrivera-t-on a terminer avant {heure}",
        "est-il possible de finir a {heure}",
        "tout sera-t-il pret pour {heure}",
        "peut-on boucler le service avant {heure}",
        "est-ce realisable avant {heure}",
        "aurons-nous termine a {heure}",
        "le planning tient-il jusqu'a {heure}",
        "peut-on respecter l'echeance de {heure}",
        "est-ce faisable dans les delais",
        "aura-t-on assez de temps avant {heure}",
        "le service peut-il s'achever a {heure}",
        "sera-t-on dans les temps pour {heure}",
        "peut-on tenir l'horaire de {heure}",
        "est-ce que {heure} est tenable",
        "aurons-nous fini les chambres avant {heure}",
        "le delai de {heure} est-il respectable",
        "peut-on achever le secteur {secteur} avant {heure}",
        "est-ce jouable avant {heure}",
    ),
    Intention.SIGNALER_PANNE_TECHNIQUE: (
        "l'{equipement_commun} est en panne",
        "l'{equipement_commun} ne fonctionne plus",
        "panne sur l'{equipement_commun}",
        "l'{equipement_commun} de l'etage {etage} est arrete",
        "probleme technique sur l'{equipement_commun}",
        "l'{equipement_commun} est hors service",
        "defaillance de l'{equipement_commun}",
        "l'{equipement_commun} s'est arrete",
        "signalement panne {equipement_commun}",
        "l'{equipement_commun} de l'etage {etage} ne repond plus",
        "avarie sur l'{equipement_commun}",
        "l'{equipement_commun} necessite une intervention",
        "dysfonctionnement de l'{equipement_commun}",
        "l'{equipement_commun} est bloque",
        "il faut reparer l'{equipement_commun}",
        "l'{equipement_commun} est immobilise",
        "panne technique a l'etage {etage}",
        "l'{equipement_commun} ne demarre pas",
        "incident technique sur l'{equipement_commun}",
        "l'{equipement_commun} est defectueux",
    ),
    Intention.QUALIFIER_GRAVITE: (
        "est-ce grave si l'{equipement_commun} est arrete",
        "quelle est la gravite de la panne sur la {chambre}",
        "est-ce urgent pour la {chambre}",
        "quelle criticite pour l'{equipement_commun}",
        "faut-il traiter la {chambre} en urgence",
        "quelle priorite donner a la {chambre}",
        "est-ce critique pour l'{equipement_commun}",
        "quelle est la portee de la panne en {chambre}",
        "cela peut-il attendre pour la {chambre}",
        "quelle gravite pour l'{equipement_commun}",
        "l'incident de la {chambre} est-il serieux",
        "quelle urgence pour l'{equipement_commun}",
        "faut-il intervenir tout de suite en {chambre}",
        "quelle est la criticite de la {chambre}",
        "est-ce prioritaire pour l'{equipement_commun}",
        "evaluer la gravite de la panne {chambre}",
        "quelle importance a l'incident en {chambre}",
        "l'arret de l'{equipement_commun} est-il critique",
        "quel niveau d'urgence pour la {chambre}",
        "apprecier la portee de la panne sur l'{equipement_commun}",
    ),
    Intention.PRIORISER_INTERVENTIONS: (
        "par quoi commencer aujourd'hui",
        "quelles interventions sont prioritaires",
        "dans quel ordre traiter les pannes",
        "quelle intervention faire en premier",
        "comment ordonner les reparations",
        "quelles reparations sont urgentes",
        "par ou commencer les interventions",
        "quelle est la priorite des reparations",
        "ordonner les interventions en attente",
        "quelles pannes traiter en priorite",
        "quel est l'ordre des interventions",
        "que doit-on reparer en premier",
        "hierarchiser les interventions",
        "quelles reparations avant les autres",
        "etablir l'ordre des reparations",
        "quelle intervention est la plus urgente",
        "priorite des travaux techniques",
        "comment classer les interventions",
        "quelles pannes sont les plus critiques",
        "sequencer les reparations du jour",
    ),
    Intention.AFFECTER_TECHNICIEN: (
        "qui peut reparer la {chambre}",
        "quel technicien pour la {chambre}",
        "affecter un technicien a la {chambre}",
        "qui envoyer sur la {chambre}",
        "quel technicien est disponible pour la {chambre}",
        "assigner {technicien} a la {chambre}",
        "qui prend en charge la {chambre}",
        "designer un technicien pour la {chambre}",
        "confier la {chambre} a un technicien",
        "quel intervenant pour la {chambre}",
        "qui est qualifie pour la {chambre}",
        "envoyer {technicien} sur la {chambre}",
        "attribuer la reparation de la {chambre}",
        "quel technicien affecter",
        "qui peut intervenir sur la {chambre}",
        "affecter {technicien} a cette reparation",
        "trouver un technicien pour la {chambre}",
        "qui traite la panne de la {chambre}",
        "designer l'intervenant de la {chambre}",
        "quel agent technique pour la {chambre}",
    ),
    Intention.CONSULTER_INTERVENTIONS: (
        "quelles interventions sont en cours",
        "combien d'interventions en attente",
        "quelles reparations sont prevues",
        "liste des interventions",
        "quelles pannes restent a traiter",
        "affiche les interventions",
        "combien de reparations en cours",
        "quelles interventions sont planifiees",
        "etat des interventions techniques",
        "quelles reparations sont ouvertes",
        "montre les interventions en attente",
        "combien de pannes signalees",
        "quelles interventions ne sont pas affectees",
        "situation de la maintenance",
        "quelles reparations sont achevees",
        "liste des travaux techniques",
        "quelles interventions pour aujourd'hui",
        "combien d'interventions au total",
        "quel est le suivi des reparations",
        "affiche l'etat de la maintenance",
    ),
    Intention.INCIDENT_AVEC_INTERVENTION: (
        "fuite en {chambre}, il faut un plombier et reloger les clients",
        "la {chambre} a un degat, prevoir reparation et relogement",
        "panne en {chambre}, envoyer un technicien et deplacer le client",
        "la {chambre} est inondee, intervention et relogement necessaires",
        "probleme en {chambre}, il faut reparer et reloger",
        "incident {chambre}, technicien et chambre de remplacement",
        "la {chambre} necessite une reparation et un relogement",
        "degat en {chambre}, traiter la panne et le client",
        "la {chambre} est hors service, reparation et deplacement du client",
        "avarie {chambre}, prevoir l'intervention et le relogement",
        "la {chambre} pose probleme, technicien plus relogement",
        "il faut reparer la {chambre} et deplacer son occupant",
        "panne grave en {chambre}, intervention et nouvelle chambre",
        "la {chambre} demande une reparation, ou loger le client",
        "incident technique {chambre}, gerer reparation et client",
        "la {chambre} est immobilisee, reparer et reloger",
        "urgence {chambre}, technicien et chambre de repli",
        "traiter la panne de la {chambre} et son occupant",
        "la {chambre} appelle une intervention et un relogement",
        "double action sur la {chambre}, reparation et deplacement",
    ),
    Intention.ARBITRER_PRIORITES: (
        "j'ai une fuite en {chambre} et l'{equipement_commun} bloque, par quoi commencer",
        "entre la {chambre} et l'{equipement_commun}, quelle priorite",
        "plusieurs urgences en meme temps, que faire en premier",
        "comment arbitrer entre la {chambre} et l'{equipement_commun}",
        "j'ai deux problemes, lequel traiter d'abord",
        "la {chambre} ou l'{equipement_commun}, quelle urgence",
        "trop de choses a traiter, par ou commencer",
        "quelle priorite entre les incidents en cours",
        "comment hierarchiser mes urgences",
        "j'ai plusieurs situations critiques simultanees",
        "que traiter en premier entre tous ces problemes",
        "arbitrer entre plusieurs urgences",
        "quelle situation est la plus critique",
        "comment ordonner les urgences du moment",
        "je ne peux pas tout traiter, que privilegier",
        "quelle est la priorite absolue maintenant",
        "aide moi a arbitrer entre les incidents",
        "plusieurs chambres et l'{equipement_commun} en panne",
        "que privilegier entre la {chambre} et le reste",
        "comment gerer plusieurs urgences a la fois",
    ),
}

PATRONS_EVALUATION: dict[Intention, tuple[str, ...]] = {
    Intention.DEGAT_DES_EAUX: (
        "la moquette de la {chambre} est trempee",
        "le plafond de la {chambre} goutte",
        "l'eau a envahi le sol de la {chambre}",
        "la {chambre} est inutilisable, tout est mouille",
        "flaque importante {localisation} de la {chambre}",
        "les affaires du client de la {chambre} sont mouillees",
    ),
    Intention.PANNE_CLIMATISATION: (
        "le compresseur de climatisation de la {chambre} est arrete",
        "aucun air frais ne sort en {chambre}",
        "la {chambre} suffoque faute de climatisation",
        "le thermostat de la {chambre} ne repond pas",
        "impossible de rafraichir l'air de la {chambre}",
        "la clim de la {chambre} demeure inactive",
    ),
    Intention.AGENT_INDISPONIBLE: (
        "{agent} nous fait faux bond sur {secteur}",
        "le poste de {agent} demeure vacant",
        "{agent} est excuse pour aujourd'hui",
        "{agent} n'assurera pas sa vacation",
        "l'agent {agent} manque a l'appel sur {secteur}",
        "aucune presence de {agent} ce matin",
    ),
    Intention.PANNE_ELECTRIQUE: (
        "l'alimentation de la {chambre} a disjoncte",
        "obscurite totale signalee chambre {chambre}",
        "aucun point lumineux actif en {chambre}",
        "la {chambre} est privee de courant electrique",
        "les prises de la {chambre} ne delivrent rien",
        "l'eclairage de la {chambre} reste eteint",
    ),
    Intention.PANNE_PLOMBERIE: (
        "la tuyauterie de la {chambre} est obstruee",
        "debit nul aux robinets de la {chambre}",
        "vidange impossible chambre {chambre}",
        "aucune eau chaude ne parvient en {chambre}",
        "le lavabo de la {chambre} refuse de se vider",
        "la douche de la {chambre} n'a plus de pression",
    ),
    Intention.DEFAUT_SERRURE: (
        "le cylindre de la {chambre} est grippe",
        "le client reste dehors, {chambre} inaccessible",
        "lecteur de badge muet en {chambre}",
        "poignee arrachee sur la {chambre}",
        "le barillet de la {chambre} refuse de tourner",
        "condamnation impossible sur la {chambre}",
        "dispositif d'ouverture inerte chambre {chambre}",
        "la {chambre} demeure inaccessible au client",
        "identification du badge echouee en {chambre}",
        "fermeture non securisee de la {chambre}",
    ),
    Intention.MOBILIER_ENDOMMAGE: (
        "l'ameublement de la {chambre} est deteriore",
        "structure du couchage rompue en {chambre}",
        "la {chambre} compte un meuble inutilisable",
        "le fauteuil de la {chambre} s'est effondre",
        "table cassee {localisation} de la {chambre}",
        "remplacement de mobilier requis en {chambre}",
    ),
    Intention.NUISANCE_SONORE: (
        "resonance permanente signalee en {chambre}",
        "la {chambre} subit les nuisances de la rue",
        "conversations audibles depuis la {chambre}",
        "grief sonore enregistre pour la {chambre}",
        "l'environnement sonore de la {chambre} est intenable",
        "propagation de bruits vers la {chambre}",
        "la {chambre} deplore un tapage continu",
        "atteinte a la tranquillite en {chambre}",
        "reverberations importantes chambre {chambre}",
        "sonorite parasite relevee dans la {chambre}",
    ),
    Intention.RISQUE_SECURITE: (
        "emanation suspecte {localisation} en {chambre}",
        "installation dangereuse relevee chambre {chambre}",
        "la {chambre} doit etre evacuee par precaution",
        "court-circuit visible {localisation} en {chambre}",
        "peril immediat constate {localisation} en {chambre}",
        "la {chambre} expose l'occupant a un danger",
        "defaut critique de securite chambre {chambre}",
        "mise en securite exigee pour la {chambre}",
        "presence d'un facteur de risque {localisation} en {chambre}",
        "la {chambre} doit etre neutralisee sans attendre",
    ),
    Intention.DEMANDE_AFFECTATION: (
        "que fait-on de {reservation} qui n'a rien",
        "il reste {reservation} a caser",
        "{reservation} attend une attribution avec {equipement}",
        "aucune chambre encore prevue pour {reservation}",
        "{reservation} demeure sans hebergement attribue",
        "il convient de placer {reservation}",
        "aucune solution d'accueil pour {reservation}",
        "{reservation} requiert {equipement} pour son sejour",
        "orienter {reservation} vers une chambre libre",
        "attribution non resolue concernant {reservation}",
    ),
    Intention.DEMANDE_AVEC_PREFERENCE: (
        "attribuer une chambre attenante a la {proximite}",
        "privilegier une chambre contigue a la {proximite}",
        "installer le client dans le voisinage de la {proximite}",
        "reserver une chambre du niveau {etage}",
        "ecarter le client de la {eloignement}",
        "prevoir un hebergement mitoyen de la {proximite}",
    ),
    Intention.INCIDENT_AVEC_PREFERENCE: (
        "avarie constatee en {chambre}, prevoir un hebergement contigu a la {proximite}",
        "la {chambre} devient inexploitable, orienter vers le niveau {etage}",
        "sinistre en {chambre}, installer le client aupres de la {proximite}",
        "la {chambre} est neutralisee, chambre mitoyenne de la {proximite}",
        "defaillance en {chambre}, ecarter le client de la {eloignement}",
        "la {chambre} sort du parc, prevoir a l'etage {etage}",
    ),
    Intention.CHANGEMENT_AVEC_PREFERENCE: (
        "reorienter {reservation} vers le voisinage de la {proximite}",
        "{reservation} sollicite le niveau {etage}",
        "transferer {reservation} en chambre attenante a la {proximite}",
        "{reservation} demande a s'ecarter de la {eloignement}",
        "permutation de {reservation} vers l'etage {etage}",
        "{reservation} souhaite un hebergement contigu a la {proximite}",
    ),
    Intention.DEMANDE_CHANGEMENT: (
        "{reservation} refuse de rester en {chambre}",
        "permutation demandee pour {reservation}",
        "la {chambre} deplait au client {reservation}",
        "prevoir un autre logement pour {reservation}",
        "{reservation} n'entend pas rester en {chambre}",
        "reaffectation sollicitee depuis la {chambre}",
        "le sejour {reservation} appelle une permutation",
        "{reservation} exige {equipement}, absent de la {chambre}",
        "orienter {reservation} vers un autre hebergement",
        "la {chambre} ne repond pas aux attentes de {reservation}",
    ),
    Intention.SIGNALEMENT_INDISPONIBILITE: (
        "la {chambre} cesse d'etre exploitable",
        "mise hors circuit de la {chambre}",
        "proscrire toute attribution de la {chambre}",
        "la {chambre} quitte le stock commercialisable",
        "ne plus vendre la {chambre} jusqu'a nouvel ordre",
        "la {chambre} est retiree des chambres louables",
    ),
    Intention.ARRIVEE_ANTICIPEE: (
        "{reservation} devance son arrivee a {heure}",
        "on nous signale {reservation} pour {heure}",
        "{reservation} a avance son horaire, {heure}",
        "presentation attendue de {reservation} des {heure}",
        "{reservation} nous informe d'une venue a {heure}",
        "accueil a preparer des {heure} pour {reservation}",
        "{reservation} raccourcit son delai d'arrivee, {heure}",
        "presentation prevue plus tot, {reservation} a {heure}",
        "{reservation} sollicite un acces anticipe a {heure}",
        "horaire ramene a {heure} concernant {reservation}",
    ),
    Intention.CHAMBRE_URGENTE: (
        "la {chambre} exige un nettoyage immediat",
        "avancer la preparation de la {chambre} pour {heure}",
        "mise a disposition urgente de la {chambre}",
        "la {chambre} doit etre propre avant {heure}",
        "reordonner le menage au profit de la {chambre}",
        "traiter la {chambre} en priorite pour {heure}",
    ),
    Intention.DEMANDE_PLANIFICATION: (
        "etablir la feuille de route de {secteur}",
        "que donne l'organisation sur {secteur}",
        "distribuer la charge du secteur {secteur}",
        "ordonner les prestations de {secteur}",
        "elaborer l'ordonnancement du secteur {secteur}",
        "quelle organisation retenir pour {secteur}",
        "ventiler la charge de travail sur {secteur}",
        "arreter le programme de service de {secteur}",
        "sequencer les prestations du secteur {secteur}",
        "batir la feuille de service de {secteur}",
    ),
    Intention.CONSULTER_PARC: (
        "de combien de chambres dispose l'etablissement",
        "quel effectif de chambres gerons nous",
        "indique le total du parc chambres",
        "l'hotel comporte combien d'unites",
        "renseigne moi sur la taille du parc",
        "quel est le decompte des chambres",
    ),
    Intention.CONSULTER_DISPONIBILITE: (
        "que reste t il d'attribuable",
        "enumere les chambres exploitables a l'etage {etage}",
        "quel est le solde de chambres pretes",
        "quelles unites sont commercialisables",
        "reste t il des chambres a proposer",
        "recense les chambres vacantes de l'etage {etage}",
    ),
    Intention.CONSULTER_INDISPONIBLES: (
        "quelles unites sont retirees du parc",
        "recense les chambres neutralisees",
        "quelles chambres sont frappees d'indisponibilite",
        "enumere les immobilisations de l'etage {etage}",
        "quelles unites echappent a l'attribution",
        "quel est l'inventaire des blocages",
    ),
    Intention.CONSULTER_ARRIVEES: (
        "quel est le flux d'accueil du jour",
        "recense les presentations attendues avant {heure}",
        "quels dossiers demeurent sans hebergement",
        "enumere les venues prevues",
        "quel volume d'accueil aujourd'hui",
        "quelles presentations sont annoncees pour {heure}",
    ),
    Intention.CONSULTER_AGENTS: (
        "quel est l'effectif mobilisable",
        "recense le personnel affecte a {secteur}",
        "quelles ressources humaines sont mobilisees",
        "enumere les intervenants de {secteur}",
        "quel est le contingent en poste",
        "qui compose la vacation du jour",
    ),
    Intention.CONSULTER_TACHES: (
        "quel est le reliquat de prestations",
        "recense les interventions attendues sur {secteur}",
        "quelle charge demeure a absorber",
        "enumere les prestations non couvertes",
        "quel volume reste a traiter sur {secteur}",
        "quel est l'encours de nettoyage",
    ),
    Intention.CONSULTER_CHAMBRE: (
        "renseigne moi sur l'unite {chambre}",
        "quelle est la situation actuelle de la {chambre}",
        "expose le dossier de la {chambre}",
        "la {chambre} presente quelles caracteristiques",
        "quel est le profil de la {chambre}",
        "restitue l'etat courant de la {chambre}",
    ),
    Intention.CONSULTER_SEJOUR: (
        "expose le dossier de {reservation}",
        "quelles sont les attentes de {reservation}",
        "restitue le contenu de {reservation}",
        "quel est le profil du client {reservation}",
        "renseigne moi sur le dossier {reservation}",
        "quelle est la teneur de {reservation}",
    ),
    Intention.CONFLIT_AFFECTATION: (
        "la {chambre} figure dans deux dossiers concurrents",
        "une collision oppose {reservation} sur la {chambre}",
        "l'unite {chambre} supporte deux engagements",
        "incompatibilite detectee entre sejours sur la {chambre}",
        "la {chambre} est promise a deux clients",
        "superposition de reservations relevee sur la {chambre}",
    ),
    Intention.SUR_OCCUPATION: (
        "la demande excede l'offre disponible",
        "l'etablissement ne peut absorber les arrivees de {heure}",
        "le parc est insuffisant pour les engagements pris",
        "nous faisons face a un depassement de capacite",
        "l'offre de chambres est epuisee",
        "les engagements depassent le parc exploitable",
    ),
    Intention.DEMANDE_CONSEIL: (
        "quelle orientation privilegier",
        "sur quelle option dois je m'arreter",
        "eclaire moi sur la conduite a tenir",
        "quel arbitrage recommandes tu",
        "vers quelle solution m'orienter",
        "quelle voie retenir face a cela",
    ),
    Intention.REPARTIR_CHARGE: (
        "ventiler {quantite} chambres sur {quantite} intervenants",
        "quelle distribution pour {quantite} unites et {quantite} agents",
        "comment allouer {quantite} agents a {quantite} chambres",
        "equilibrage de {quantite} prestations entre {quantite} personnes",
        "affecter {quantite} intervenants a {quantite} chambres",
        "repartition de la charge: {quantite} chambres, {quantite} agents",
    ),
    Intention.CONSULTER_CHARGE: (
        "quel volume demeure sur {secteur}",
        "combien d'heures restent a couvrir",
        "quelle est l'estimation temporelle du service",
        "duree previsionnelle pour {secteur}",
        "quel encours horaire sur {secteur}",
        "combien de temps mobilise le secteur {secteur}",
    ),
    Intention.ESTIMER_FAISABILITE: (
        "l'echeance de {heure} est-elle atteignable",
        "le service peut-il aboutir avant {heure}",
        "sommes-nous en mesure de finir a {heure}",
        "la contrainte horaire de {heure} tient-elle",
        "peut-on conclure avant {heure}",
        "l'objectif de {heure} demeure-t-il realiste",
    ),
    Intention.SIGNALER_PANNE_TECHNIQUE: (
        "l'{equipement_commun} presente une defaillance",
        "immobilisation de l'{equipement_commun}",
        "l'{equipement_commun} du niveau {etage} est inoperant",
        "cessation de service de l'{equipement_commun}",
        "l'{equipement_commun} requiert une remise en etat",
        "anomalie technique relevee sur l'{equipement_commun}",
    ),
    Intention.QUALIFIER_GRAVITE: (
        "quelle portee a l'arret de l'{equipement_commun}",
        "comment apprecier l'incident de la {chambre}",
        "quel degre d'urgence pour l'{equipement_commun}",
        "l'incident en {chambre} appelle-t-il une reaction immediate",
        "evaluer la criticite de l'{equipement_commun}",
        "quelle incidence a la panne de la {chambre}",
    ),
    Intention.PRIORISER_INTERVENTIONS: (
        "quel enchainement retenir pour les reparations",
        "quelles interventions appellent le traitement le plus prompt",
        "arreter l'ordre de passage des techniciens",
        "quelle sequence pour les travaux",
        "hierarchiser les remises en etat",
        "quel ordonnancement des interventions",
    ),
    Intention.AFFECTER_TECHNICIEN: (
        "quel intervenant designer pour la {chambre}",
        "a qui confier la remise en etat de la {chambre}",
        "quelle ressource technique mobiliser sur la {chambre}",
        "designer l'agent competent pour la {chambre}",
        "vers qui orienter la reparation de la {chambre}",
        "attribuer l'intervention de la {chambre}",
    ),
    Intention.CONSULTER_INTERVENTIONS: (
        "quel est l'encours de maintenance",
        "recense les remises en etat prevues",
        "quel volume de reparations demeure",
        "enumere les travaux techniques ouverts",
        "quel est l'etat du suivi technique",
        "restitue les interventions enregistrees",
    ),
    Intention.INCIDENT_AVEC_INTERVENTION: (
        "la {chambre} exige une remise en etat et un deplacement d'occupant",
        "sinistre en {chambre}, mobiliser un technicien et reloger",
        "double traitement requis sur la {chambre}",
        "la {chambre} appelle reparation technique et hebergement de repli",
        "avarie {chambre}: intervenir et deplacer le client",
        "prevoir technicien et relogement pour la {chambre}",
    ),
    Intention.ARBITRER_PRIORITES: (
        "quelle urgence prevaut entre les situations en cours",
        "sur quoi porter l'effort en premier",
        "quel incident appelle le traitement le plus prompt",
        "departager les urgences simultanees",
        "quelle situation mobiliser prioritairement",
        "comment trancher entre plusieurs urgences",
    ),
}
