"""Patrons de formulation par intention."""

from .taxonomie import Intention

PATRONS_ENTRAINEMENT: dict[Intention, tuple[str, ...]] = {
    Intention.DEGAT_DES_EAUX: (
        "fuite d'eau {localisation} de la {chambre}",
        "il y a une fuite dans la {chambre}",
        "de l'eau coule {localisation} en {chambre}",
        "la {chambre} est inondee",
        "infiltration signalee {chambre}",
        "le client de la {chambre} signale une fuite",
        "eau au sol dans la {chambre}",
        "fuite {localisation} chambre {chambre}",
        "la {chambre} prend l'eau {localisation}",
        "ca fuit {localisation} de la {chambre}",
        "grosse fuite constatee dans la {chambre}",
        "on signale de l'eau {localisation} en {chambre}",
        "la {chambre} presente une infiltration {localisation}",
        "urgence plomberie, la {chambre} est noyee",
        "le sol de la {chambre} est detrempe",
        "un ecoulement se produit {localisation} chambre {chambre}",
        "la {chambre} doit etre vidangee, il y a de l'eau",
        "arrivee d'eau incontrolee en {chambre}",
        "le client de la {chambre} a les pieds dans l'eau",
        "probleme grave d'eau {localisation} en {chambre}",
        "la {chambre} n'est plus habitable, fuite {localisation}",
        "signalement urgent, eau dans la {chambre}",
        "l'eau s'accumule {localisation} de la {chambre}",
        "il pleut {localisation} de la {chambre}",
        "la {chambre} est touchee par une fuite",
        "l'etancheite a cede {localisation} en {chambre}",
        "eau stagnante relevee dans la {chambre}",
        "on constate un suintement {localisation} chambre {chambre}",
        "la {chambre} subit un degat des eaux",
        "intervention demandee, fuite {chambre}",
    ),
    Intention.PANNE_CLIMATISATION: (
        "la clim de la {chambre} ne marche plus",
        "climatisation en panne {chambre}",
        "la {chambre} n'a plus de climatisation",
        "probleme de clim en {chambre}",
        "clim hs {chambre}",
        "la climatisation de la {chambre} ne demarre pas",
        "pas de froid dans la {chambre}",
        "la clim souffle chaud en {chambre}",
        "la {chambre} etouffe, plus de clim",
        "l'appareil de climatisation de la {chambre} est arrete",
        "aucune ventilation dans la {chambre}",
        "la clim de la {chambre} tourne sans refroidir",
        "il fait une chaleur insupportable en {chambre}",
        "climatisation a reparer chambre {chambre}",
        "la {chambre} signale un dysfonctionnement de clim",
        "plus aucun reglage de temperature en {chambre}",
        "la clim s'arrete toute seule dans la {chambre}",
        "systeme de climatisation defaillant {chambre}",
        "le client de la {chambre} reclame pour la clim",
        "la {chambre} n'est plus climatisee",
        "panne de ventilation en {chambre}",
        "la clim de la {chambre} fuit et ne refroidit plus",
        "temperature ingerable dans la {chambre}",
        "clim en derangement chambre {chambre}",
        "le groupe froid de la {chambre} est arrete",
        "impossible de rafraichir la {chambre}",
        "la {chambre} demande une intervention sur la clim",
        "climatisation muette en {chambre}",
    ),
    Intention.AGENT_INDISPONIBLE: (
        "{agent} est absent aujourd'hui",
        "{agent} ne viendra pas travailler",
        "l'agent {agent} est en arret",
        "{agent} du secteur {secteur} est absent",
        "on n'a plus {agent} sur {secteur}",
        "absence de {agent}",
        "il manque {agent} sur le secteur {secteur}",
        "l'agent {agent} n'a pas pris son service",
        "on ne compte plus sur {agent} aujourd'hui",
        "{agent} s'est fait porter pale",
        "l'equipe de {secteur} perd {agent}",
        "prevoir sans {agent} sur {secteur}",
        "{agent} ne repond pas, probablement absent",
        "indisponibilite de {agent} signalee",
        "il faut reorganiser, {agent} manque",
        "{agent} a un souci et ne prend pas son poste",
        "le secteur {secteur} tourne sans {agent}",
        "{agent} est declare indisponible",
        "aucun signe de {agent} ce matin",
        "{agent} a pose un arret de travail",
        "l'effectif de {secteur} est ampute de {agent}",
        "{agent} ne sera pas la de la journee",
        "absence non prevue de {agent} sur {secteur}",
        "{agent} previent d'un retard important",
        "on doit couvrir le poste de {agent}",
        "{agent} est retenu et ne viendra pas",
        "defection de {agent} sur le secteur {secteur}",
        "plus d'agent {agent} disponible",
    ),
    Intention.PANNE_ELECTRIQUE: (
        "plus d'electricite dans la {chambre}",
        "panne de courant {chambre}",
        "la {chambre} n'a plus de lumiere",
        "coupure electrique en {chambre}",
        "les prises de la {chambre} ne fonctionnent plus",
        "probleme electrique signale {chambre}",
        "disjoncteur saute en {chambre}",
        "le client de la {chambre} n'a plus de courant",
        "la {chambre} est privee de courant",
        "black-out signale en {chambre}",
        "aucune alimentation electrique chambre {chambre}",
        "le circuit de la {chambre} a saute",
        "plus rien ne s'allume dans la {chambre}",
        "panne generale d'electricite en {chambre}",
        "les lampes de la {chambre} restent eteintes",
        "courant absent dans la {chambre}",
        "defaut electrique constate chambre {chambre}",
        "la {chambre} n'a plus d'alimentation",
        "coupure totale en {chambre}",
        "le client de la {chambre} est sans lumiere",
        "installation electrique hors service {chambre}",
        "la {chambre} demande une intervention electrique",
        "plus de courant aux prises de la {chambre}",
        "electricite coupee chambre {chambre}",
        "la {chambre} est dans le noir complet",
        "dysfonctionnement electrique en {chambre}",
        "le disjoncteur de la {chambre} ne tient plus",
        "alimentation defaillante dans la {chambre}",
    ),
    Intention.PANNE_PLOMBERIE: (
        "le lavabo de la {chambre} est bouche",
        "probleme de plomberie {localisation} en {chambre}",
        "la douche de la {chambre} ne s'ecoule plus",
        "wc bouches {chambre}",
        "pas d'eau chaude dans la {chambre}",
        "evacuation bouchee {localisation} chambre {chambre}",
        "la robinetterie de la {chambre} est defectueuse",
        "chasse d'eau hs en {chambre}",
        "l'eau ne s'evacue plus {localisation} en {chambre}",
        "engorgement signale chambre {chambre}",
        "la {chambre} n'a plus de pression d'eau",
        "probleme sanitaire {localisation} dans la {chambre}",
        "le siphon de la {chambre} est obstrue",
        "la douche de la {chambre} deborde",
        "plomberie a revoir {localisation} chambre {chambre}",
        "aucun ecoulement en {chambre}",
        "le client de la {chambre} n'a pas d'eau chaude",
        "les sanitaires de la {chambre} sont hors service",
        "canalisation bouchee {localisation} en {chambre}",
        "la {chambre} signale un refoulement",
        "robinet bloque dans la {chambre}",
        "eau froide seulement en {chambre}",
        "la {chambre} demande une intervention plomberie",
        "evier obstrue {localisation} chambre {chambre}",
        "la chasse de la {chambre} ne se remplit plus",
        "fuite au niveau du robinet de la {chambre}",
        "installation sanitaire defaillante en {chambre}",
        "la {chambre} a un probleme d'evacuation {localisation}",
    ),
    Intention.DEFAUT_SERRURE: (
        "la serrure de la {chambre} ne fonctionne plus",
        "impossible d'ouvrir la {chambre}",
        "le badge ne marche pas sur la {chambre}",
        "probleme de cle en {chambre}",
        "la porte de la {chambre} ne ferme plus",
        "serrure bloquee {chambre}",
        "le client de la {chambre} n'arrive pas a entrer",
        "verrou defectueux chambre {chambre}",
        "le client de la {chambre} est bloque dehors",
        "carte magnetique refusee sur la {chambre}",
        "mecanisme de fermeture defaillant chambre {chambre}",
        "la porte de la {chambre} reste ouverte",
        "on ne peut plus verrouiller la {chambre}",
        "le lecteur de la {chambre} clignote rouge",
        "acces impossible a la {chambre}",
        "serrure a remplacer sur la {chambre}",
        "la cle de la {chambre} tourne dans le vide",
        "probleme de fermeture en {chambre}",
        "la {chambre} ne se securise plus",
        "le pene de la {chambre} est bloque",
        "badge non reconnu chambre {chambre}",
        "ouverture forcee necessaire pour la {chambre}",
        "la {chambre} demande une intervention serrurerie",
        "dysfonctionnement du verrou en {chambre}",
        "la poignee de la {chambre} tourne sans effet",
        "impossible de condamner la {chambre}",
        "systeme d'acces hors service {chambre}",
        "le client ne peut pas entrer en {chambre}",
    ),
    Intention.MOBILIER_ENDOMMAGE: (
        "le fauteuil de la {chambre} est casse",
        "mobilier endommage {localisation} en {chambre}",
        "la {chambre} a un meuble abime",
        "tiroir casse dans la {chambre}",
        "le bureau de la {chambre} est raye",
        "degradation constatee {localisation} chambre {chambre}",
        "la television de la {chambre} est tombee",
        "lit abime en {chambre}",
        "meuble casse a remplacer en {chambre}",
        "le client de la {chambre} signale une degradation",
        "equipement abime {localisation} de la {chambre}",
        "la chaise de la {chambre} est hors d'usage",
        "revetement arrache {localisation} chambre {chambre}",
        "la table de nuit de la {chambre} est cassee",
        "mobilier a reparer en {chambre}",
        "l'armoire de la {chambre} ne ferme plus",
        "degradation constatee en {chambre}",
        "le canape de la {chambre} est tache et dechire",
        "element de mobilier defectueux chambre {chambre}",
        "la {chambre} necessite un remplacement de meuble",
        "vitrage du meuble brise en {chambre}",
        "le lit de la {chambre} grince et penche",
        "usure excessive {localisation} de la {chambre}",
        "materiel endommage signale {chambre}",
        "la {chambre} presente du mobilier detériore",
        "pied casse sur un meuble de la {chambre}",
        "rangement inutilisable en {chambre}",
        "reparation mobilier demandee chambre {chambre}",
    ),
    Intention.NUISANCE_SONORE: (
        "bruit important dans la {chambre}",
        "le client de la {chambre} se plaint du bruit",
        "nuisance sonore signalee {chambre}",
        "la {chambre} est trop bruyante",
        "plainte pour tapage en {chambre}",
        "il y a du vacarme dans la {chambre}",
        "bruits de travaux genent la {chambre}",
        "la {chambre} entend tout du couloir",
        "reclamation pour bruit chambre {chambre}",
        "le voisinage derange la {chambre}",
        "tapage nocturne signale en {chambre}",
        "la {chambre} ne peut pas dormir a cause du bruit",
        "nuisance persistante dans la {chambre}",
        "bruit de tuyauterie genant la {chambre}",
        "le client de la {chambre} demande un autre etage, trop bruyant",
        "vacarme continu en {chambre}",
        "isolation phonique insuffisante chambre {chambre}",
        "la {chambre} subit des nuisances repetees",
        "plainte sonore deposee pour la {chambre}",
        "bruits de pas incessants au-dessus de la {chambre}",
        "la {chambre} entend la ventilation en permanence",
        "gene acoustique signalee en {chambre}",
        "musique trop forte pres de la {chambre}",
        "la {chambre} est expose au bruit de la rue",
        "reclamation acoustique chambre {chambre}",
        "impossible de se reposer en {chambre}",
        "bruit anormal detecte dans la {chambre}",
        "le calme n'est pas assure en {chambre}",
    ),
    Intention.RISQUE_SECURITE: (
        "odeur de gaz {localisation} en {chambre}",
        "risque de securite signale {chambre}",
        "detecteur de fumee declenche en {chambre}",
        "cable electrique denude {localisation} chambre {chambre}",
        "danger immediat dans la {chambre}",
        "depart de feu suspecte en {chambre}",
        "la {chambre} presente un risque pour le client",
        "vitre brisee {localisation} en {chambre}",
        "danger signale {localisation} en {chambre}",
        "la {chambre} doit etre condamnee immediatement",
        "installation a risque chambre {chambre}",
        "fumee constatee {localisation} de la {chambre}",
        "alerte securite pour la {chambre}",
        "situation dangereuse en {chambre}",
        "la {chambre} presente un peril pour l'occupant",
        "evacuation preventive de la {chambre}",
        "anomalie grave relevee {localisation} chambre {chambre}",
        "risque d'accident en {chambre}",
        "la {chambre} n'est pas securisee",
        "element dangereux {localisation} dans la {chambre}",
        "intervention urgente securite {chambre}",
        "la {chambre} doit etre inspectee sans delai",
        "manquement a la securite constate en {chambre}",
        "odeur suspecte {localisation} de la {chambre}",
        "la {chambre} presente un danger electrique",
        "signalement securite prioritaire chambre {chambre}",
        "acces a interdire pour la {chambre}",
        "menace pour l'integrite du client en {chambre}",
    ),
    Intention.DEMANDE_AFFECTATION: (
        "quelle chambre pour {reservation}",
        "il faut affecter une chambre a {reservation}",
        "{reservation} arrive sans chambre",
        "trouver une chambre pour {reservation} avec {equipement}",
        "affectation a faire pour {reservation}",
        "on doit loger {reservation}",
        "chambre a attribuer a {reservation}",
        "{reservation} demande une chambre avec {equipement}",
        "loger {reservation} qui arrive",
        "il faut une chambre pour {reservation}",
        "attribution en attente pour {reservation}",
        "{reservation} n'a toujours pas de chambre",
        "prevoir l'hebergement de {reservation}",
        "quelle chambre convient a {reservation}",
        "traiter l'affectation de {reservation}",
        "{reservation} necessite une chambre avec {equipement}",
        "chercher un logement pour {reservation}",
        "{reservation} est en attente d'attribution",
        "chambre a designer pour {reservation}",
        "l'arrivee {reservation} reste sans solution",
        "affecter {reservation} au plus vite",
        "{reservation} demande {equipement} dans sa chambre",
        "trouver ou installer {reservation}",
        "placement a faire pour {reservation}",
        "{reservation} arrive et rien n'est prevu",
        "designer une chambre a {reservation}",
        "il reste {reservation} sans hebergement",
        "attribuer une chambre disposant de {equipement} a {reservation}",
    ),
    Intention.DEMANDE_CHANGEMENT: (
        "il faut deplacer {reservation} de la {chambre}",
        "changement de chambre pour {reservation}",
        "{reservation} veut quitter la {chambre}",
        "reloger {reservation} qui est en {chambre}",
        "la {chambre} ne convient pas a {reservation}",
        "{reservation} demande une autre chambre avec {equipement}",
        "transferer {reservation} hors de la {chambre}",
        "le client de la {chambre} souhaite changer",
        "{reservation} souhaite quitter la {chambre}",
        "reloger le client de la {chambre}",
        "la {chambre} ne satisfait pas {reservation}",
        "prevoir une permutation pour {reservation}",
        "{reservation} demande a changer de la {chambre}",
        "deplacer l'occupant de la {chambre}",
        "changement demande par {reservation}",
        "{reservation} veut une chambre avec {equipement}",
        "sortir {reservation} de la {chambre}",
        "reaffecter {reservation} actuellement en {chambre}",
        "le sejour {reservation} doit etre transfere",
        "la {chambre} pose probleme a {reservation}",
        "prevoir un autre hebergement pour {reservation}",
        "{reservation} reclame un changement de chambre",
        "muter {reservation} vers une autre chambre",
        "le client {reservation} refuse la {chambre}",
        "attribuer une nouvelle chambre a {reservation}",
        "la {chambre} doit etre liberee pour {reservation}",
        "{reservation} demande {equipement}, la {chambre} n'en a pas",
        "transfert a organiser depuis la {chambre}",
    ),
    Intention.SIGNALEMENT_INDISPONIBILITE: (
        "la {chambre} est indisponible",
        "bloquer la {chambre}",
        "mettre la {chambre} hors service",
        "la {chambre} ne peut plus etre louee",
        "retirer la {chambre} de la vente",
        "chambre {chambre} immobilisee",
        "ne plus attribuer la {chambre}",
        "la {chambre} passe en maintenance",
        "la {chambre} sort du parc",
        "ne plus proposer la {chambre}",
        "immobiliser la {chambre} jusqu'a reparation",
        "la {chambre} est inexploitable",
        "suspendre la {chambre}",
        "marquer la {chambre} comme indisponible",
        "la {chambre} ne doit plus recevoir de client",
        "exclure la {chambre} des affectations",
        "la {chambre} passe hors exploitation",
        "condamner temporairement la {chambre}",
        "la {chambre} n'est plus commercialisable",
        "geler la {chambre} pour intervention",
        "retirer la {chambre} du planning",
        "la {chambre} devient inoccupable",
        "interdire l'attribution de la {chambre}",
        "la {chambre} est mise a l'ecart",
        "bloquer definitivement la {chambre}",
        "la {chambre} est retiree de la disponibilite",
        "cesser de louer la {chambre}",
        "la {chambre} requiert une immobilisation",
    ),
    Intention.ARRIVEE_ANTICIPEE: (
        "{reservation} arrive a {heure}",
        "arrivee anticipee de {reservation} vers {heure}",
        "{reservation} se presente des {heure}",
        "le client {reservation} sera la a {heure}",
        "{reservation} annonce une arrivee a {heure}",
        "arrivee avancee pour {reservation}",
        "{reservation} arrive plus tot que prevu, {heure}",
        "prevenir que {reservation} vient a {heure}",
        "{reservation} sera la des {heure}",
        "avancer l'arrivee de {reservation} a {heure}",
        "{reservation} demande a entrer a {heure}",
        "le client {reservation} arrive tot, {heure}",
        "presentation anticipee de {reservation}",
        "{reservation} previent qu'il arrive vers {heure}",
        "arrivee revue a {heure} pour {reservation}",
        "{reservation} souhaite acceder des {heure}",
        "prevoir {reservation} pour {heure}",
        "le sejour {reservation} commence a {heure}",
        "{reservation} devance l'horaire, {heure}",
        "arrivee plus matinale de {reservation}",
        "{reservation} se presentera a {heure}",
        "horaire avance signale pour {reservation}",
        "{reservation} arrive avant l'heure prevue",
        "acces demande a {heure} par {reservation}",
        "{reservation} annonce {heure} comme arrivee",
        "anticiper l'accueil de {reservation} a {heure}",
        "le client {reservation} est attendu des {heure}",
        "modification d'horaire pour {reservation}, {heure}",
    ),
    Intention.CHAMBRE_URGENTE: (
        "la {chambre} doit etre prete pour {heure}",
        "preparer la {chambre} en urgence",
        "il faut la {chambre} avant {heure}",
        "nettoyage prioritaire pour la {chambre}",
        "la {chambre} est attendue a {heure}",
        "faire passer la {chambre} en priorite",
        "chambre {chambre} urgente pour {heure}",
        "traiter la {chambre} en premier",
        "la {chambre} passe en priorite absolue",
        "il faut la {chambre} au plus vite",
        "traiter la {chambre} avant {heure}",
        "la {chambre} est attendue en urgence",
        "nettoyer la {chambre} en premier",
        "la {chambre} doit etre livree pour {heure}",
        "prioriser le nettoyage de la {chambre}",
        "la {chambre} est reclamee immediatement",
        "avancer la preparation de la {chambre}",
        "remise en etat urgente de la {chambre}",
        "la {chambre} devient prioritaire pour {heure}",
        "faire la {chambre} sans attendre",
        "urgence sur la {chambre}",
        "la {chambre} doit etre disponible a {heure}",
        "placer la {chambre} en tete du planning",
        "preparation immediate demandee chambre {chambre}",
        "la {chambre} ne peut pas attendre",
        "traitement prioritaire pour la {chambre}",
        "la {chambre} est requise pour {heure}",
        "acceler la mise en ordre de la {chambre}",
    ),
    Intention.DEMANDE_PLANIFICATION: (
        "organiser le service du secteur {secteur}",
        "planifier le nettoyage sur {secteur}",
        "il faut faire le planning de {secteur}",
        "repartir les chambres du secteur {secteur}",
        "planification demandee pour {secteur}",
        "organiser les etages sur {secteur}",
        "faire le tour de service de {secteur}",
        "affecter les taches du secteur {secteur}",
        "etablir le planning du secteur {secteur}",
        "repartir le travail sur {secteur}",
        "organiser les taches de {secteur}",
        "planifier les chambres du secteur {secteur}",
        "il faut ordonner le service de {secteur}",
        "distribuer les prestations sur {secteur}",
        "preparer la journee du secteur {secteur}",
        "affecter les agents de {secteur}",
        "quel planning pour {secteur}",
        "organiser le nettoyage du secteur {secteur}",
        "calculer le tour de service de {secteur}",
        "le secteur {secteur} attend son planning",
        "repartition a faire sur {secteur}",
        "ordonnancer les taches du secteur {secteur}",
        "mettre en place le service de {secteur}",
        "planification du secteur {secteur} demandee",
        "attribuer les chambres aux agents de {secteur}",
        "structurer la journee de {secteur}",
        "il faut planifier {secteur}",
        "definir l'ordre de passage sur {secteur}",
    ),
}

PATRONS_EVALUATION: dict[Intention, tuple[str, ...]] = {
    Intention.DEGAT_DES_EAUX: (
        "la moquette de la {chambre} est trempee",
        "le plafond de la {chambre} goutte",
        "l'eau a envahi le sol de la {chambre}",
        "la {chambre} est inutilisable, tout est mouille",
        "flaque importante {localisation} de la {chambre}",
        "les affaires du client de la {chambre} sont mouillees",
    ),
    Intention.PANNE_CLIMATISATION: (
        "le compresseur de climatisation de la {chambre} est arrete",
        "aucun air frais ne sort en {chambre}",
        "la {chambre} suffoque faute de climatisation",
        "le thermostat de la {chambre} ne repond pas",
        "impossible de rafraichir l'air de la {chambre}",
        "la clim de la {chambre} demeure inactive",
    ),
    Intention.AGENT_INDISPONIBLE: (
        "{agent} nous fait faux bond sur {secteur}",
        "le poste de {agent} demeure vacant",
        "{agent} est excuse pour aujourd'hui",
        "{agent} n'assurera pas sa vacation",
        "l'agent {agent} manque a l'appel sur {secteur}",
        "aucune presence de {agent} ce matin",
    ),
    Intention.PANNE_ELECTRIQUE: (
        "l'alimentation de la {chambre} a disjoncte",
        "obscurite totale signalee chambre {chambre}",
        "aucun point lumineux actif en {chambre}",
        "la {chambre} est privee de courant electrique",
        "les prises de la {chambre} ne delivrent rien",
        "l'eclairage de la {chambre} reste eteint",
    ),
    Intention.PANNE_PLOMBERIE: (
        "la tuyauterie de la {chambre} est obstruee",
        "debit nul aux robinets de la {chambre}",
        "vidange impossible chambre {chambre}",
        "aucune eau chaude ne parvient en {chambre}",
        "le lavabo de la {chambre} refuse de se vider",
        "la douche de la {chambre} n'a plus de pression",
    ),
    Intention.DEFAUT_SERRURE: (
        "le cylindre de la {chambre} est grippe",
        "le client reste dehors, {chambre} inaccessible",
        "lecteur de badge muet en {chambre}",
        "poignee arrachee sur la {chambre}",
        "le barillet de la {chambre} refuse de tourner",
        "condamnation impossible sur la {chambre}",
        "dispositif d'ouverture inerte chambre {chambre}",
        "la {chambre} demeure inaccessible au client",
        "identification du badge echouee en {chambre}",
        "fermeture non securisee de la {chambre}",
    ),
    Intention.MOBILIER_ENDOMMAGE: (
        "l'ameublement de la {chambre} est deteriore",
        "structure du couchage rompue en {chambre}",
        "la {chambre} compte un meuble inutilisable",
        "le fauteuil de la {chambre} s'est effondre",
        "table cassee {localisation} de la {chambre}",
        "remplacement de mobilier requis en {chambre}",
    ),
    Intention.NUISANCE_SONORE: (
        "resonance permanente signalee en {chambre}",
        "la {chambre} subit les nuisances de la rue",
        "conversations audibles depuis la {chambre}",
        "grief sonore enregistre pour la {chambre}",
        "l'environnement sonore de la {chambre} est intenable",
        "propagation de bruits vers la {chambre}",
        "la {chambre} deplore un tapage continu",
        "atteinte a la tranquillite en {chambre}",
        "reverberations importantes chambre {chambre}",
        "sonorite parasite relevee dans la {chambre}",
    ),
    Intention.RISQUE_SECURITE: (
        "emanation suspecte {localisation} en {chambre}",
        "installation dangereuse relevee chambre {chambre}",
        "la {chambre} doit etre evacuee par precaution",
        "court-circuit visible {localisation} en {chambre}",
        "peril immediat constate {localisation} en {chambre}",
        "la {chambre} expose l'occupant a un danger",
        "defaut critique de securite chambre {chambre}",
        "mise en securite exigee pour la {chambre}",
        "presence d'un facteur de risque {localisation} en {chambre}",
        "la {chambre} doit etre neutralisee sans attendre",
    ),
    Intention.DEMANDE_AFFECTATION: (
        "que fait-on de {reservation} qui n'a rien",
        "il reste {reservation} a caser",
        "{reservation} attend une attribution avec {equipement}",
        "aucune chambre encore prevue pour {reservation}",
        "{reservation} demeure sans hebergement attribue",
        "il convient de placer {reservation}",
        "aucune solution d'accueil pour {reservation}",
        "{reservation} requiert {equipement} pour son sejour",
        "orienter {reservation} vers une chambre libre",
        "attribution non resolue concernant {reservation}",
    ),
    Intention.DEMANDE_CHANGEMENT: (
        "{reservation} refuse de rester en {chambre}",
        "permutation demandee pour {reservation}",
        "la {chambre} deplait au client {reservation}",
        "prevoir un autre logement pour {reservation}",
        "{reservation} n'entend pas rester en {chambre}",
        "reaffectation sollicitee depuis la {chambre}",
        "le sejour {reservation} appelle une permutation",
        "{reservation} exige {equipement}, absent de la {chambre}",
        "orienter {reservation} vers un autre hebergement",
        "la {chambre} ne repond pas aux attentes de {reservation}",
    ),
    Intention.SIGNALEMENT_INDISPONIBILITE: (
        "la {chambre} cesse d'etre exploitable",
        "mise hors circuit de la {chambre}",
        "proscrire toute attribution de la {chambre}",
        "la {chambre} quitte le stock commercialisable",
        "ne plus vendre la {chambre} jusqu'a nouvel ordre",
        "la {chambre} est retiree des chambres louables",
    ),
    Intention.ARRIVEE_ANTICIPEE: (
        "{reservation} devance son arrivee a {heure}",
        "on nous signale {reservation} pour {heure}",
        "{reservation} a avance son horaire, {heure}",
        "presentation attendue de {reservation} des {heure}",
        "{reservation} nous informe d'une venue a {heure}",
        "accueil a preparer des {heure} pour {reservation}",
        "{reservation} raccourcit son delai d'arrivee, {heure}",
        "presentation prevue plus tot, {reservation} a {heure}",
        "{reservation} sollicite un acces anticipe a {heure}",
        "horaire ramene a {heure} concernant {reservation}",
    ),
    Intention.CHAMBRE_URGENTE: (
        "la {chambre} exige un nettoyage immediat",
        "avancer la preparation de la {chambre} pour {heure}",
        "mise a disposition urgente de la {chambre}",
        "la {chambre} doit etre propre avant {heure}",
        "reordonner le menage au profit de la {chambre}",
        "traiter la {chambre} en priorite pour {heure}",
    ),
    Intention.DEMANDE_PLANIFICATION: (
        "etablir la feuille de route de {secteur}",
        "que donne l'organisation sur {secteur}",
        "distribuer la charge du secteur {secteur}",
        "ordonner les prestations de {secteur}",
        "elaborer l'ordonnancement du secteur {secteur}",
        "quelle organisation retenir pour {secteur}",
        "ventiler la charge de travail sur {secteur}",
        "arreter le programme de service de {secteur}",
        "sequencer les prestations du secteur {secteur}",
        "batir la feuille de service de {secteur}",
    ),
}
