"""Patrons de formulation par intention."""

from .taxonomie import Intention

PATRONS_ENTRAINEMENT: dict[Intention, tuple[str, ...]] = {
    Intention.DEGAT_DES_EAUX: (
        "fuite d'eau {localisation} de la {chambre}",
        "il y a une fuite dans la {chambre}",
        "de l'eau coule {localisation} en {chambre}",
        "la {chambre} est inondee",
        "infiltration signalee {chambre}",
        "le client de la {chambre} signale une fuite",
        "eau au sol dans la {chambre}",
        "fuite {localisation} chambre {chambre}",
        "la {chambre} prend l'eau {localisation}",
        "ca fuit {localisation} de la {chambre}",
    ),
    Intention.PANNE_CLIMATISATION: (
        "la clim de la {chambre} ne marche plus",
        "climatisation en panne {chambre}",
        "la {chambre} n'a plus de climatisation",
        "probleme de clim en {chambre}",
        "clim hs {chambre}",
        "la climatisation de la {chambre} ne demarre pas",
        "pas de froid dans la {chambre}",
        "la clim souffle chaud en {chambre}",
    ),
    Intention.AGENT_INDISPONIBLE: (
        "{agent} est absent aujourd'hui",
        "{agent} ne viendra pas travailler",
        "l'agent {agent} est en arret",
        "{agent} du secteur {secteur} est absent",
        "on n'a plus {agent} sur {secteur}",
        "absence de {agent}",
        "il manque {agent} sur le secteur {secteur}",
        "l'agent {agent} n'a pas pris son service",
    ),
    Intention.PANNE_ELECTRIQUE: (
        "plus d'electricite dans la {chambre}",
        "panne de courant {chambre}",
        "la {chambre} n'a plus de lumiere",
        "coupure electrique en {chambre}",
        "les prises de la {chambre} ne fonctionnent plus",
        "probleme electrique signale {chambre}",
        "disjoncteur saute en {chambre}",
        "le client de la {chambre} n'a plus de courant",
    ),
    Intention.PANNE_PLOMBERIE: (
        "le lavabo de la {chambre} est bouche",
        "probleme de plomberie {localisation} en {chambre}",
        "la douche de la {chambre} ne s'ecoule plus",
        "wc bouches {chambre}",
        "pas d'eau chaude dans la {chambre}",
        "evacuation bouchee {localisation} chambre {chambre}",
        "la robinetterie de la {chambre} est defectueuse",
        "chasse d'eau hs en {chambre}",
    ),
    Intention.DEFAUT_SERRURE: (
        "la serrure de la {chambre} ne fonctionne plus",
        "impossible d'ouvrir la {chambre}",
        "le badge ne marche pas sur la {chambre}",
        "probleme de cle en {chambre}",
        "la porte de la {chambre} ne ferme plus",
        "serrure bloquee {chambre}",
        "le client de la {chambre} n'arrive pas a entrer",
        "verrou defectueux chambre {chambre}",
    ),
    Intention.MOBILIER_ENDOMMAGE: (
        "le fauteuil de la {chambre} est casse",
        "mobilier endommage {localisation} en {chambre}",
        "la {chambre} a un meuble abime",
        "tiroir casse dans la {chambre}",
        "le bureau de la {chambre} est raye",
        "degradation constatee {localisation} chambre {chambre}",
        "la television de la {chambre} est tombee",
        "lit abime en {chambre}",
    ),
    Intention.NUISANCE_SONORE: (
        "bruit important dans la {chambre}",
        "le client de la {chambre} se plaint du bruit",
        "nuisance sonore signalee {chambre}",
        "la {chambre} est trop bruyante",
        "plainte pour tapage en {chambre}",
        "il y a du vacarme dans la {chambre}",
        "bruits de travaux genent la {chambre}",
        "la {chambre} entend tout du couloir",
    ),
    Intention.RISQUE_SECURITE: (
        "odeur de gaz {localisation} en {chambre}",
        "risque de securite signale {chambre}",
        "detecteur de fumee declenche en {chambre}",
        "cable electrique denude {localisation} chambre {chambre}",
        "danger immediat dans la {chambre}",
        "depart de feu suspecte en {chambre}",
        "la {chambre} presente un risque pour le client",
        "vitre brisee {localisation} en {chambre}",
    ),
    Intention.DEMANDE_AFFECTATION: (
        "quelle chambre pour {reservation}",
        "il faut affecter une chambre a {reservation}",
        "{reservation} arrive sans chambre",
        "trouver une chambre pour {reservation} avec {equipement}",
        "affectation a faire pour {reservation}",
        "on doit loger {reservation}",
        "chambre a attribuer a {reservation}",
        "{reservation} demande une chambre avec {equipement}",
    ),
    Intention.DEMANDE_CHANGEMENT: (
        "il faut deplacer {reservation} de la {chambre}",
        "changement de chambre pour {reservation}",
        "{reservation} veut quitter la {chambre}",
        "reloger {reservation} qui est en {chambre}",
        "la {chambre} ne convient pas a {reservation}",
        "{reservation} demande une autre chambre avec {equipement}",
        "transferer {reservation} hors de la {chambre}",
        "le client de la {chambre} souhaite changer",
    ),
    Intention.SIGNALEMENT_INDISPONIBILITE: (
        "la {chambre} est indisponible",
        "bloquer la {chambre}",
        "mettre la {chambre} hors service",
        "la {chambre} ne peut plus etre louee",
        "retirer la {chambre} de la vente",
        "chambre {chambre} immobilisee",
        "ne plus attribuer la {chambre}",
        "la {chambre} passe en maintenance",
    ),
    Intention.ARRIVEE_ANTICIPEE: (
        "{reservation} arrive a {heure}",
        "arrivee anticipee de {reservation} vers {heure}",
        "{reservation} se presente des {heure}",
        "le client {reservation} sera la a {heure}",
        "{reservation} annonce une arrivee a {heure}",
        "arrivee avancee pour {reservation}",
        "{reservation} arrive plus tot que prevu, {heure}",
        "prevenir que {reservation} vient a {heure}",
    ),
    Intention.CHAMBRE_URGENTE: (
        "la {chambre} doit etre prete pour {heure}",
        "preparer la {chambre} en urgence",
        "il faut la {chambre} avant {heure}",
        "nettoyage prioritaire pour la {chambre}",
        "la {chambre} est attendue a {heure}",
        "faire passer la {chambre} en priorite",
        "chambre {chambre} urgente pour {heure}",
        "traiter la {chambre} en premier",
    ),
    Intention.DEMANDE_PLANIFICATION: (
        "organiser le service du secteur {secteur}",
        "planifier le nettoyage sur {secteur}",
        "il faut faire le planning de {secteur}",
        "repartir les chambres du secteur {secteur}",
        "planification demandee pour {secteur}",
        "organiser les etages sur {secteur}",
        "faire le tour de service de {secteur}",
        "affecter les taches du secteur {secteur}",
    ),
}

PATRONS_EVALUATION: dict[Intention, tuple[str, ...]] = {
    Intention.DEGAT_DES_EAUX: (
        "une canalisation a lache {localisation} de la {chambre}",
        "la moquette de la {chambre} est trempee",
        "ruissellement signale en {chambre}",
        "le plafond de la {chambre} goutte",
    ),
    Intention.PANNE_CLIMATISATION: (
        "l'air conditionne de la {chambre} est mort",
        "impossible de regler la temperature en {chambre}",
        "unite de climatisation defectueuse {chambre}",
        "le thermostat de la {chambre} ne repond pas",
    ),
    Intention.AGENT_INDISPONIBLE: (
        "{agent} vient de se declarer souffrant",
        "personne pour remplacer {agent} sur {secteur}",
        "{agent} a un empechement pour la journee",
        "effectif reduit, {agent} manquant",
    ),
    Intention.PANNE_ELECTRIQUE: (
        "la {chambre} est plongee dans le noir",
        "aucun eclairage ne repond en {chambre}",
        "le tableau electrique a lache pour la {chambre}",
        "alimentation coupee chambre {chambre}",
    ),
    Intention.PANNE_PLOMBERIE: (
        "l'ecoulement de la {chambre} refoule",
        "canalisation obstruee {localisation} en {chambre}",
        "la {chambre} n'a qu'un filet d'eau",
        "siphon bouche chambre {chambre}",
    ),
    Intention.DEFAUT_SERRURE: (
        "le cylindre de la {chambre} est grippe",
        "le client reste dehors, {chambre} inaccessible",
        "lecteur de badge muet en {chambre}",
        "poignee arrachee sur la {chambre}",
    ),
    Intention.MOBILIER_ENDOMMAGE: (
        "un pied de table casse {localisation} en {chambre}",
        "le sommier de la {chambre} s'est effondre",
        "revetement decolle {localisation} chambre {chambre}",
        "miroir felé dans la {chambre}",
    ),
    Intention.NUISANCE_SONORE: (
        "resonance permanente signalee en {chambre}",
        "la {chambre} subit les nuisances de la rue",
        "conversations audibles depuis la {chambre}",
        "reclamation acoustique chambre {chambre}",
    ),
    Intention.RISQUE_SECURITE: (
        "emanation suspecte {localisation} en {chambre}",
        "installation dangereuse relevee chambre {chambre}",
        "la {chambre} doit etre evacuee par precaution",
        "court-circuit visible {localisation} en {chambre}",
    ),
    Intention.DEMANDE_AFFECTATION: (
        "que fait-on de {reservation} qui n'a rien",
        "il reste {reservation} a caser",
        "{reservation} attend une attribution avec {equipement}",
        "aucune chambre encore prevue pour {reservation}",
    ),
    Intention.DEMANDE_CHANGEMENT: (
        "{reservation} refuse de rester en {chambre}",
        "permutation demandee pour {reservation}",
        "la {chambre} deplait au client {reservation}",
        "prevoir un autre logement pour {reservation}",
    ),
    Intention.SIGNALEMENT_INDISPONIBILITE: (
        "condamner la {chambre} jusqu'a nouvel ordre",
        "la {chambre} sort du parc commercialisable",
        "suspendre la commercialisation de la {chambre}",
        "chambre {chambre} a exclure des attributions",
    ),
    Intention.ARRIVEE_ANTICIPEE: (
        "{reservation} devance son arrivee a {heure}",
        "on nous signale {reservation} pour {heure}",
        "{reservation} a avance son horaire, {heure}",
        "presentation attendue de {reservation} des {heure}",
    ),
    Intention.CHAMBRE_URGENTE: (
        "la {chambre} est reclamee pour {heure}",
        "remise en etat immediate de la {chambre}",
        "avancer la {chambre} avant {heure}",
        "la {chambre} passe en tete de liste",
    ),
    Intention.DEMANDE_PLANIFICATION: (
        "etablir la feuille de route de {secteur}",
        "que donne l'organisation sur {secteur}",
        "distribuer la charge du secteur {secteur}",
        "ordonner les prestations de {secteur}",
    ),
}
